version: '3.8'

networks:
  mynetwork:
    external: true
    driver: bridge

services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - mynetwork

  # MailDev service
  maildev:
    image: maildev/maildev
    container_name: maildev_container
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - mynetwork

  # Spring Boot app service
  app:
    build:
      context: . # Assuming the Dockerfile is in the same directory as docker-compose.yml
    container_name: demo_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - mynetwork

volumes:
  postgres_data:
